name: CI

on: [push]

permissions:
  contents: read

jobs:

  lint:

    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Lint newlines
        uses: fionn/newline-linter@v1.0.3

      - name: Lint Go
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.12.2

      - name: Check formatting
        run: test -z "$(gofmt -l .)"

      - name: Check dependency tidiness
        run: go mod tidy -diff

      - name: Check for vulnerable dependency use
        run: go tool govulncheck -format sarif ./... | jq "(.runs[].tool.driver.rules[]?.properties.tags)? |= unique" > govulncheck.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4.35.5
        with:
          sarif_file: govulncheck.sarif
          category: govulncheck

  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v

      - name: Install gh extension
        run: gh extension install .

      - name: Execute
        run: gh inspect-push "$GITHUB_SHA"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute with JSON
        run: gh inspect-push --json "$GITHUB_SHA" | jq .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
